"use strict";
const form=document.getElementById("courseForm"),result=document.getElementById("result");
const put=(id,text)=>document.getElementById(id).textContent=text;
form.addEventListener("submit",event=>{
 event.preventDefault();
 const read=id=>document.getElementById(id).value;
 const need=read("need"),audience=read("audience"),level=read("level"),barrier=read("barrier"),cases=read("cases");
 const goals=[...form.querySelectorAll('[name="outcome"]:checked')].map(el=>el.value);
 if(!goals.length){put("error","Selecione pelo menos um resultado prioritário.");form.querySelector('[name="outcome"]').focus();return;}put("error","");
 const management=audience==="managers";
 const a=level==="low"?"Fundamentos de CP, identificação de necessidades, avaliação multidimensional, comunicação, ética e planejamento do cuidado.":level==="mixed"?"Avaliação diagnóstica e núcleo comum nivelador, com percursos diferenciados por lacunas.":"Revisão dirigida pelas lacunas identificadas; fundamentos essenciais e discussão de situações complexas.";
 const b=management?"Competências compartilhadas com as equipes: comunicação, colaboração, coordenação do cuidado e compreensão das necessidades de pacientes e famílias.":"Comunicação, trabalho interprofissional, planejamento do cuidado e coordenação. Selecionar competências compartilhadas entre os grupos profissionais participantes.";
 const c=management?"Planejamento e implementação da rede, indicadores, qualidade, acesso e educação permanente.":audience==="specific"?"Aprofundamento das competências da categoria selecionada, respeitando suas atribuições e limites de atuação.":"Trilhas diferenciadas por categoria profissional; incluir trilha de gestão quando houver gestores.";
 const d=cases==="yes"?"Caso real com dados desidentificados, teleconsultoria, feedback e plano de aplicação no serviço.":cases==="limited"?"Casos contextualizados, telementoria e aplicação supervisionada quando possível.":"Casos simulados progressivos, discussão estruturada e plano de transferência para a prática.";
 const target=document.getElementById("modules");target.replaceChildren();
 [["A · Núcleo comum",a],["B · Competências compartilhadas",b],["C · Núcleo profissional",c],["D · Aplicação e telessaúde",d]].forEach(([title,text])=>{const card=document.createElement("article");card.className="module";const h=document.createElement("h3"),p=document.createElement("p");h.textContent=title;p.textContent=text;card.append(h,p);target.append(card);});
 let ped="Orientação andragógica, problematização e aprendizagem experiencial: conteúdos breves, casos, reflexão e feedback.";
 if(need==="basic")ped+=" Progredir dos fundamentos para situações mais complexas.";
 if(need==="gap")ped+=" Mapear lacunas e alinhar cada atividade a um objetivo observável.";
 if(goals.includes("knowledge"))ped+=" Usar recuperação espaçada e quizzes com feedback.";
 if(goals.includes("skill"))ped+=" Incluir simulação e avaliação de desempenho com critérios explícitos.";
 if(need==="practice"||goals.includes("practice"))ped+=" Priorizar decisões e planos aplicáveis ao serviço.";put("pedagogy",ped);
 let tele=cases==="yes"?"Combinar teleducação, discussão de casos e teleconsultoria para problemas assistenciais reais, com retorno sobre a aplicação.":"Combinar teleducação síncrona e assíncrona com telementoria e discussão estruturada de casos.";
 if(need==="network"||goals.includes("service"))tele+=" Manter encontros recorrentes e comunidade de prática para apoiar a rede.";put("telehealth",tele);
 let fmt=barrier==="time"||barrier==="both"?"Microblocos assíncronos e encontros síncronos curtos, com percurso flexível.":"Atividades assíncronas, avaliações formativas e encontros síncronos.";
 if(barrier==="digital"||barrier==="both")fmt+=" Oferecer materiais leves para celular, download e suporte inicial.";
 fmt+=" Estimar a carga horária pela soma das atividades necessárias a cada competência, incluindo estudo e aplicação.";put("format",fmt);
 let ev="Acompanhar participação, conclusão, satisfação e experiência qualitativa.";
 if(goals.includes("knowledge"))ev+=" Avaliar conhecimento antes e após o curso e, quando viável, sua manutenção posterior.";
 if(goals.includes("skill"))ev+=" Avaliar desempenho em casos com rubrica; medir autoeficácia separadamente.";
 if(goals.includes("practice")||need==="practice")ev+=" Planejar seguimento em 60–90 dias para verificar transferência para a prática.";
 if(goals.includes("service")||need==="network")ev+=" Monitorar indicadores de processo e implementação definidos no diagnóstico.";put("assessment",ev);
 result.hidden=false;result.focus();result.scrollIntoView({behavior:"smooth",block:"start"});
});
form.addEventListener("reset",()=>{result.hidden=true;put("error","");});
document.getElementById("print").addEventListener("click",()=>window.print());
