'use client';
import {nearestInstitutions,needsInstitutionalSupport,supportMethod} from '../lib/institutional-support';
import {dissertationAlerts} from '../lib/dissertation-alerts';
import {planningChecklist} from '../lib/planning-checklist';
import {connectivityQuality} from '../lib/connectivity-quality';
import {needsConference} from '../lib/summary-modality';
import {requirementSummary} from '../lib/platform-requirements';
import type {TrailState} from '../lib/trail';
import type {Municipality} from '../lib/connectivity';
import {summaryRows,finalGuidance} from '../lib/course-summary';
import {courseDecision} from '../lib/course-decision';
import {rankPlatforms} from '../lib/platform-compatibility';
import {createSummaryPdf,type PdfSummary} from '../lib/summary-pdf';
import {CheckCircle2,Download} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
type Props={values:TrailState;data:{municipality:Municipality;mode:string;retrieved:string}|null;plan:ReturnType<typeof courseDecision>;production:string;pending:string[]};
const num=(v:number|null)=>v===null?'Sem dado':v.toLocaleString('pt-BR',{maximumFractionDigits:1});
export default function FinalSummary({values,data,plan,production,pending}:Props){
 const summary=summaryRows(values,data?.municipality??null),guidance=finalGuidance(values,plan.modality,production,pending),ranking=rankPlatforms(values),target=useRef<HTMLElement>(null);
 const [downloading,setDownloading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{target.current?.focus();target.current?.scrollIntoView({block:'start',behavior:'smooth'})},[]);
 const teaching=[ranking.teachingSuggestion?`${ranking.teachingSuggestion.platform} · ${ranking.teachingReason}`:'Sugestão de ensino pendente: confirmar requisitos.'];
 const showConference=needsConference(plan.modality);
 const acsAlert=dissertationAlerts(values,ranking).tracks;
 const checklist=planningChecklist(values,!!data,showConference);
 const conference=showConference?[ranking.conferenceSuggestion?`${ranking.conferenceSuggestion.platform} · ${ranking.conferenceReason}`:'Sugestão de videoconferência pendente: confirmar requisitos e acesso.']:[];
 const rankingNote=(showConference?`Videoconferência: ${ranking.mode==='audio'?'somente áudio':'vídeo'}. `:'')+`Sugestões baseadas nos requisitos informados, estrutura existente e referência municipal de banda. Confirmar recursos, serviço e conexão local antes da oferta.`;
 const quality=connectivityQuality(values,ranking,showConference);
 const connectivity=ranking.measured?`Anatel · internet móvel: download médio ${values.download} Mbps; upload médio ${values.upload} Mbps. Referência ${values.measurementDate}. Validar a conexão local.`:'Medições municipais não utilizadas ou indisponíveis.';
 const supportNeeded=needsInstitutionalSupport(values),institutions=supportNeeded?nearestInstitutions(values.id):[];
 const institutionalSupport=supportNeeded?(institutions.length?[...institutions.map((i,n)=>`${n===0?'Instituição mais próxima':'Alternativa'}: ${i.name} — ${i.city}/${i.uf}; aproximadamente ${Math.round(i.distance)} km em linha reta. ${[i.email,i.phone].filter(Boolean).join(' · ')}. Fonte: ${i.source}`),supportMethod]:['Selecione um município com coordenadas disponíveis para identificar a instituição mais próxima.']):[];
 const pdf:PdfSummary={checklist,acsAlert,institutionalSupport,territory:summary.territory,audience:summary.audience,goal:summary.goal,guidance:guidance.title,action:guidance.action,modality:plan.modality,production,connectivity:connectivity+` Classificação: ${quality.label}.`,connectivityDetails:`${quality.detail} ${quality.teaching} ${quality.method}`,teaching,conference,rankingNote,pending,pedagogicalPriority:plan.actions[3].action,requirements:requirementSummary(values).filter(([label])=>showConference||!["Plataforma de videoconferência já disponível","Recursos indispensáveis nos encontros","O serviço atual atende ao tamanho da turma, encontros simultâneos e recursos necessários?","Turmas ou reuniões simultâneas"].includes(label)).map(([k,v])=>`${k}: ${v}`)};
 async function download(){setDownloading(true);setError('');try{const logos=await Promise.all(['logo-unifesp.png','logo-telenordeste.png','logo-bp.png'].map(async file=>{const response=await fetch(import.meta.env.BASE_URL+file);if(!response.ok)throw new Error('Logo indisponível');const blob=await response.blob();return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}));const doc=await createSummaryPdf({...pdf,logos});doc.save(`Plano_CP_${values.id||'municipio-pendente'}.pdf`)}catch{setError('Não foi possível gerar o PDF. Tente novamente.')}finally{setDownloading(false)}}
 return <section className="final-summary summary-compact" ref={target} tabIndex={-1} aria-labelledby="summary-title"><div className="institutional-logos summary-logos" aria-label="Instituições do estudo e do projeto"><img src={import.meta.env.BASE_URL+"logo-unifesp.png"} alt="Unifesp"/><img src={import.meta.env.BASE_URL+"logo-telenordeste.png"} alt="TeleNordeste"/><img src={import.meta.env.BASE_URL+"logo-bp.png"} alt="BP — Beneficência Portuguesa de São Paulo"/></div><div className="summary-heading"><CheckCircle2 size={24}/><div><span className="eyebrow">TRILHA CONCLUÍDA</span><h2 id="summary-title">Resultado do fluxo decisório para planejamento de teleducação em cuidados paliativos</h2><p>{summary.territory} · {summary.audience}</p></div><button type="button" className="pdf-download" onClick={download} disabled={downloading}><Download size={17}/>{downloading?'Gerando…':'Baixar PDF'}</button></div>{error&&<p role="alert" className="error">{error}</p>}
 <div className="summary-guidance"><b>{guidance.title}</b><p>{guidance.action}</p></div><dl className="summary-conditions"><div><dt>Objetivo</dt><dd>{summary.goal}</dd></div><div><dt>Modalidade</dt><dd>{plan.modality}</dd></div><div><dt>Produção</dt><dd>{production}</dd></div><div><dt>Prioridade pedagógica</dt><dd>{plan.actions[3].action}</dd></div></dl>
 <div className="summary-rankings" style={showConference?undefined:{gridTemplateColumns:"1fr"}}><div><h3>Plataforma sugerida de ensino</h3><ol>{teaching.map(t=><li key={t}>{t}</li>)}</ol></div>{showConference&&<div><h3>Plataforma sugerida de videoconferência · {ranking.mode==='audio'?'áudio':'vídeo'}</h3><ol>{conference.map(t=><li key={t}>{t}</li>)}</ol></div>}</div><p className="small">Plataformas sugeridas conforme requisitos informados; validar a conexão local e os planos. Critérios e fontes disponíveis nas etapas anteriores.</p>
 <div className={`connectivity-quality reference-compact quality-${quality.level}`}><h3>Conectividade de referência</h3><b className="reference-status">{quality.label}</b><p className="small">{ranking.measured?`↓ ${values.download} Mbps · ↑ ${values.upload} Mbps · Anatel, ${values.measurementDate}`:connectivity}</p><details><summary>Detalhes e critérios</summary><p>{quality.detail}</p><p>{quality.teaching}</p><p>{quality.method}</p><p className="small">Média municipal de internet móvel; validar a conexão local.</p></details></div>
 {supportNeeded&&<div className="summary-next institutional-support"><h3>Apoio institucional pedagógico</h3>{institutions.length?institutions.map((i,n)=><div key={i.name}><b>{i.name}</b><p className="support-location">{n===0?'Mais próxima':'Alternativa'} · {i.city}/{i.uf} · ≈ {Math.round(i.distance).toLocaleString('pt-BR')} km</p><p>{i.email&&<a href={`mailto:${i.email}`}>{i.email}</a>}{i.email&&i.phone?' · ':''}{i.phone}</p><a href={i.source} target="_blank" rel="noreferrer">Fonte do contato</a></div>):<p>Selecione um município com coordenadas disponíveis para identificar a instituição mais próxima.</p>}<details className="support-method"><summary>Critérios e disponibilidade</summary><p className="small">{supportMethod}</p></details></div>}
 {acsAlert&&<aside className="stage-evidence dissertation-alert" role="status"><span className="eyebrow">ALERTA · ACS E AQUISIÇÃO DE CONHECIMENTO</span><p>{acsAlert}</p><small>Lima, Unifesp, 2026 · §§ 5.4, 5.5 e 6.2</small></aside>}
 <div className="summary-next planning-checklist"><h3>Checklist do planejamento · {checklist.filter(i=>i.done).length}/{checklist.length} atendidos</h3><p className="small">Situação conforme as respostas informadas no fluxo.</p><ul>{checklist.map(i=><li key={i.label} className={i.done?'checklist-done':'checklist-pending'}><span aria-hidden="true">{i.done?'☑':'☐'}</span><span><b>{i.done?'Já feito':'Falta fazer'}</b> · {i.label}</span></li>)}</ul></div>
 <details className="summary-details"><summary>Ver respostas e fundamentação</summary><p>{plan.rationale}</p><dl className="summary-conditions">{summary.rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="small">{connectivity}</p><p className="small">{rankingNote}</p><p className="small">Avaliação: participação, conclusão, conhecimento e autoeficácia pré/pós, satisfação, barreiras e aplicação no serviço.</p><p className="small">Fundamentação: dados oficiais da Anatel e achados de Lima (Unifesp, 2026). Recomendações para planejamento.</p></details><p className="small summary-note">Baixe o PDF para guardar o plano. As respostas serão apagadas ao recarregar a página.</p></section>;
}
