import {useState} from 'react';
import type {TrailState} from '../lib/trail';
import {rankPlatforms} from '../lib/platform-compatibility';
import {connectivityQuality} from '../lib/connectivity-quality';
type Props={values:TrailState;onChange:(v:Partial<TrailState>)=>void;municipal:{download:number;upload:number;period:string}|null};
export default function LocalConnection({values,onChange,municipal}:Props){
 const [test,setTest]=useState(values.measurementSource==='local-test'?{measurementPlace:values.measurementPlace,measurementDate:values.measurementDate,download:values.download,upload:values.upload,devices:values.devices,local:values.local}:{measurementPlace:'',measurementDate:'',download:'',upload:'',devices:'1',local:'unknown'});
 const active=values.measurementSource==='local-test';
 function update(key:keyof typeof test,value:string){const next={...test,[key]:value};setTest(next);onChange({...next,measurementSource:'local-test'});}
 const ranking=rankPlatforms(values),quality=connectivityQuality(values,ranking);
 return <div className="local-connection"><p className="small"><a href="https://simet.nic.br/" target="_blank" rel="noopener noreferrer">Testar a conexão no local — SIMET/NIC.br</a></p><p className="small">Se desejar, abra o teste conectado à internet da unidade e registre abaixo os resultados de download e upload.</p><label className="inline-check"><input type="checkbox" checked={active} onChange={e=>onChange(e.target.checked?{...test,measurementSource:'local-test'}:municipal?{download:String(municipal.download),upload:String(municipal.upload),measurementDate:municipal.period,measurementPlace:'Referência municipal',devices:'1',local:'unknown',measurementSource:'anatel-municipal'}:{measurementSource:'',download:'',upload:''})}/>Referência de conectividade do entorno</label>{active&&<><p className="small">Informe os resultados de um teste no local de interesse. Os dados municipais permanecem acima; as sugestões e o resumo usarão o teste informado. Este campo não realiza consulta automática a dados do entorno.</p><div className="form-grid"><label>Unidade/bairro e local do teste<input value={test.measurementPlace} onChange={e=>update('measurementPlace',e.target.value)} placeholder="Ex.: UBS Central · bairro Centro"/></label><label>Data do teste<input type="date" value={test.measurementDate} onChange={e=>update('measurementDate',e.target.value)}/></label><label>Download (Mbps)<input type="number" min="0" step="any" value={test.download} onChange={e=>update('download',e.target.value)}/></label><label>Upload (Mbps)<input type="number" min="0" step="any" value={test.upload} onChange={e=>update('upload',e.target.value)}/></label><label>Dispositivos simultâneos na conexão<input type="number" min="1" step="1" value={test.devices} onChange={e=>update('devices',e.target.value)}/></label><label>Estabilidade observada<select value={test.local} onChange={e=>update('local',e.target.value)}><option value="unknown">Ainda não confirmada</option><option value="stable">Estável no teste</option><option value="limited">Instável ou com interrupções</option></select></label></div><div className={`connectivity-quality reference-compact quality-${quality.level}`} role="status"><b>Conectividade no local testado · {quality.label}</b><p className="small">{quality.detail}</p></div><p className="small">Teste a conexão no horário do curso. A medição representa o local e momento testados, não todo o bairro. Bandas divididas pelo número de dispositivos para planejamento.</p></>}</div>;
}
